apiVersion: v1
kind: Service
metadata:
  name: {{ include "openclaw.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.gateway.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.browser.novncPort }}
      targetPort: {{ .Values.browser.novncPort }}
      protocol: TCP
      name: novnc
  selector:
    {{- include "openclaw.selectorLabels" . | nindent 4 }}
